project:
  type: website
  output-dir: docs

website:
  title: "Zain Nofal | Data Science Blog"
  navbar:
    left:
      - text: Posts
        href: index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/zainnofal
      - icon: linkedin
        href: https://www.linkedin.com/in/zainnofal/

format:
  html:
    theme: Minty
    css: styles.css
    toc: false
    smooth-scroll: true
